model_name_or_path: "../model/Qwen3-1.7B"
datasets:
  - path: "trl-lib/Capybara"
learning_rate: 2e-5
test_split_size: 0.1
dataset_train_split: "train"
dataset_eval_split: "test"
num_epochs: 1
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
gradient_checkpointing: true
eval_strategy: "steps"
eval_steps: 100
output_dir: "/data/satori_hdd1/mutyuu/workspace/trl/research/alignment/model/Qwen3-1.7B-sft-random"
push_to_hub: true